---
date: "2020-02-05T12:22:34"
description: This is meta description.
image: images/blog/post-7.jpg
title: Spannungsbogen 
---
Non conosco il tedesco, ma questa parola mi ha subito colpito, la trovo di una profondità così immersiva che tocca il fondo del mio mare di sentimenti. _Spannung_ non è una parola nuova, si studia al liceo nella letteratura italiana, è una delle poche parole rubate al tedesco. Significa Suspence, momento topico. Per capirsi lo spannung è quando Hansel e Gretel stanno per finire dentro il forno, quando in Robin Hood, appunto Robin Hood finisce in galera. Il momento di _spannung_ è anche un momento di _crisis_ non anticipa l'epilogo, ma è un nuovo inizio, un nuovo personaggio sta nascendo, o un nuovo mondo sta arrivando. Ci deve sempre essere una crisi, una spaccatura tra una situazione vecchia ed una nuova, se si è alla ricerca di una mutazione. Lo scrittore Frank Herbert nella sua collezione di libri Dune scrive:

" I Fremen erano i supremi maestri della qualità che gli antichi chiamavano "spannungsbogen": l'imposizione volontaria di un indugio fra il desiderio di una cosa e l'atto di procurarsela."  
 -- <cite>**Frank Herbert**</cite>
 
 
Ora non ci interessa più di tanto il contesto che caratterizza il libro, che è di fantascienza, ciò che vale la pena notare invece è come viene definita la parola. Quello che noto è che oggi siamo abituati a misurare il successo sugli obiettivi raggiunti, pertanto definisco di successo chi mette più medaglie in fila sulla spalla, viceversa fallito chi rimane nudo. Qui l'ottica è diversa: la facile lettura de "l'attesa del piacere è essa stessa il piacere" è semplicistica, qui c'è la potenzialità di poterla raggiungere, un desiderio di averla, ma tutto questo viene chiuso con un razionale indugio, con un veloce ragionato no. Trovo tutto questo la massima espressione della ragione, una grande privazione degna di un auto controllo smisurato. Qui i risultati si misurano sui no detti, su quelle che si ritengono opportunità perse, su una sorta di camera dei trofei chiusa in una cantina, dove nessuno andrà mai a guardare. La possibilità rimane tuttavia aperta, la partita è rigiocabile, la scacchiera è cambiata ma i giocatori sono sempre gli stessi. Oggi nessuno vuole fare più il prete, quindi negarsi il sesso, la massima espressione di godimento e libertà concepita oggi. Quanto sarebbe in controtendenza ed eversivo invece schierarsi di là, dove nessuno vuole stare. Ci vogliono tante palle.  Questo determina un personalissimo concetto di successo, totalmente slegato dai risulati degli altri e in ultima analisi l'unica strada percorribile per un'esistenza felice e pacifica. 